name: "Setup env"
description: "Sets up node and installs yarn dependencies"
runs:
  using: "composite"
  steps:
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: yarn
    - run: yarn
      shell: bash
