name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Export and deploy app
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: export files
        run: yarn export
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
